name: test2
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build and Test
        run: |
          echo "Hello world 2"
          # Add your build and test commands here
